version: '3.5'
services:
  db:
    build: postgresql
    image: afisha_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - afisha_ntwrk
  pgadmin:
    build: pgadmin
    image: afisha_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - afisha_ntwrk
  swagger-ui:
    build: swagger-ui
    image: afisha_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - afisha_ntwrk

  EventFilmService:
    build: Films
    image: film-service:1.0.0
    networks:
      - afisha_ntwrk
  EventConcertService:
    build: Concerts
    image: concert-service:1.0.0
    networks:
      - afisha_ntwrk
  ClassifierService:
    build: Classifier
    image: classifier-service:1.0.0
    networks:
      - afisha_ntwrk
  UserService:
    build: Users
    image: user-service:1.0.0
    networks:
      - afisha_ntwrk

  proxy:
    build: proxy
    image: afisha_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - afisha_ntwrk
networks:
  afisha_ntwrk:
    name: afisha_ntwrk