spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/users_db?currentSchema=users
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

app:
  db:
    host: localhost
    port: 5432

error:
  include-message: ALWAYS
  include-stacktrace: NEVER

