spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/classifier?currentSchema=countries_and_categories
    driver-class-name: org.postgresql.Driver

server:
  port: 80

app:
  db:
    host: localhost
    port: 5432