spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/concerts?currentSchema=concert_events
    driver-class-name: org.postgresql.Driver

server:
  port: 8084

app:
  db:
    host: localhost
    port: 5432